version: '3.8'
services:
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-latest}
    container_name: grafana
    hostname: grafana
    ports:
      - 3000:3000 # default port for grafana
    volumes:
      - ./grafana:/var/lib/grafana
    user: root
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - ${GLOBAL_NETWORK:-grafana}
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-latest}
    container_name: prometheus
    hostname: prometheus
    ports:
      - 9090:9090 # default port for prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml # passing prometheus config data
      - ./prometheus:/prometheus
    user: root
    networks:
      - ${GLOBAL_NETWORK:-prometheus}
