version: '3.8'
services:
  redis-master:
    image: redis:${REDIS_VERSION:-latest}
    container_name: redis-master
    hostname: redis # pay attention here as in services.yml file we use this hostname
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "6379:6379"
    networks:
      - ${GLOBAL_NETWORK:-redis}
  redis-slave:
    image: redis:${REDIS_VERSION:-latest}
    container_name: redis-slave
    hostname: redis-slave
    command: [ "redis-server", "--slaveof", "redis-master", "6379" ]
    ports:
      - "6380:6379"
    depends_on:
      - redis-master
    networks:
      - ${GLOBAL_NETWORK:-redis}
