# Multiple eureka instances can register one with another
eureka:
  client:
    register-with-eureka: true # Tells this Eureka client to register with other Eureka servers
    fetch-registry: true # Tells this Eureka client to fetch registries from other Eureka instances
  instance:
    appname: service-registry-cluster
  server: # this service is defined as server
    enable-self-preservation: false # this tells eureka to NOT try to recover if it doesn't get heartbeat from a client, But, by default, Eureka is configured to wait for a configured time before evicting the client for higher resiliency, as temporary network outage can always happen. So with value set to false, we forced Eureka not to try to recover, but to evict the instances/clients that are unreachable.
    expected-client-renewal-interval-seconds: 3 # 30 by default for production;
    eviction-interval-timer-in-ms: 2000 # interval that eviction tasks scan for instances with expired leases; this way, discovery service will check the service's reachability for every 2 seconds, and if it's not reachable, evict it immediately.

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false # will be using spring load baalncer for load balancer, instead of netflix eureka Ribbon client-side load balancer
  profiles:
    active: singleserver

# https://stackoverflow.com/questions/50788277/why-3-dashes-hyphen-in-yaml-file
# in short, --- starts new yaml document in the same stream

---
server:
  port: 8761
spring:
  profiles: peer1
eureka:
  instance:
    hostname: discovery-service-1
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:{random.value}}
  client:
    service-url:
      defaultZone: http://discovery-service-1:8761/eureka/,http://discovery-service-2:8762/eureka/

---
server:
  port: 8762
spring:
  profiles: peer2
eureka:
  instance:
    hostname: discovery-service-2
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:{random.value}}
  client:
    service-url:
      defaultZone: http://discovery-service-2:8762/eureka/,http://discovery-service-1:8761/eureka/
