{
 "title": "microservices-demo",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "elastic-query-service-1 memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"elastic-query-service-1\", area=\"heap\"}",
     "legendFormat": "{{job}} {{id}}"
    }
   ]
  },
  {
   "title": "elastic-query-service-2 memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"elastic-query-service-2\", area=\"heap\"}",
     "legendFormat": "{{job}} {{id}}"
    }
   ]
  },
  {
   "title": "elastic-query-service-2 request/second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"elastic-query-service-2\", uri=\"/documents/get-document-by-text\"}"
    }
   ]
  },
  {
   "title": "elastic-query-service-1 request/second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"elastic-query-service-1\", uri=\"/documents/get-document-by-text\"}"
    }
   ]
  },
  {
   "title": "gateway-service-2 live threads",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"gateway-service-2\"}"
    }
   ]
  },
  {
   "title": "gateway-service-1 live threads",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"gateway-service-1\"}"
    }
   ]
  },
  {
   "title": "gateway-service-2 CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"gateway-service-2\"}"
    }
   ]
  },
  {
   "title": "gateway-service-1 CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"gateway-service-1\"}"
    }
   ]
  },
  {
   "title": "analytics-service avg. response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{job=\"analytics-service\", uri=\"/get-word-count-by-word/{word}\"} / http_server_requests_seconds_count{job=\"analytics-service\", uri=\"/get-word-count-by-word/{word}\"}"
    }
   ]
  },
  {
   "title": "services logged errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "logback_events_total{job=\"elastic-query-service-1\", level=\"error\"}"
    },
    {
     "expr": "logback_events_total{job=\"elastic-query-service-2\", level=\"error\"}"
    },
    {
     "expr": "logback_events_total{job=\"analytics-service\", level=\"error\"}"
    },
    {
     "expr": "logback_events_total{job=\"kafka-streams-service\", level=\"error\"}"
    },
    {
     "expr": "logback_events_total{job=\"gateway-service\", level=\"error\"}"
    }
   ]
  }
 ]
}