# properties placed here will override properties from config-server-repository

# once these were in bootstrap.yml properties
spring:
  application:
    name: kafka-to-elastic-service
  profiles:
    active: kafka_to_elastic # from config-client-kafka_to_elastic
  config:
    import: 'configserver:' # since I do not set URI here, it will default to http://localhost:8888, so if it's not available application startup will fail
  cloud:
    config:
      name: kafka-to-elastic-service,config-client # we use this prefix 'config-client' in config-server-repository
      #uri: http://localhost:8888 # deprecated in favor of spring.config.import
      username: spring_cloud_user
      password: '{cipher}b85c7486c68ac64035003e3317c0477b6917ede7bd2ac356f52e898217b9a1cc10c8014347787758da2167e2e53931c8'
