# properties placed here will override properties from config-server-repository

logging:
  level:
    root: debug

# override services.yml setup for now
elastic-query-web-client:
  webclient:
    instances:
      -
        id: elastic-query-service-1
        host: localhost
        port: 8183
#      -
#        id: elastic-query-service-2
#        host: localhost
#        port: 8185

# once these were in bootstrap.yml properties
spring:
  application:
    name: elastic-query-web-client-2
  profiles:
    active: elastic_query_web_client_2 # from config-client-elastic_query_web_client
  config:
    import: 'configserver:' # since I do not set URI here, it will default to http://localhost:8888, so if it's not available application startup will fail
  cloud:
    config:
      name: elastic-query-web-client,config-client # we use this prefix 'config-client' in config-server-repository
      #uri: http://localhost:8888 # deprecated in favor of spring.config.import from Spring Boot 2.4.0
      username: spring_cloud_user
      password: '{cipher}d4403ce6ae8fc4002dcc4b21bc8051da2488ac0f8f9baceb1888d1676a1104e489abd0658f83ffc2bee354322a4e8aba'