server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/filip194/config-server-repository
          default-label: master # this is branch name that will be used to get configuration data, GitHub by default now uses 'main' so this might have to be set manually, otherwise Spring Boot will set this label to 'master' by default
          username: filip194
          password:  # should not use password directly, create token at github page: https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/
          #uri: file://home/efildra/microservices-demo/config-server-repository # not a good practice
          clone-on-start: true
    fail-fast: true
  security:
    user: # we will have to add this to twitter_to_kafka_service as this config data will be propagated to that service
      name: spring_cloud_user
      password: springCloud_Pwd!

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG