server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: file://home/efildra/microservices-demo/config-server-repository
          clone-on-start: true
    fail-fast: true

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG